# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true

# AndroidX
android.useAndroidX=true

# Use this property to specify which architecture you want to build.
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# Use the new React Native architecture (Fabric + TurboModules).
newArchEnabled=true

# Use Hermes JS engine.
hermesEnabled=true
